[project]
name = "structured-compositional-reasoning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "datasets>=2.14.4",
    "huggingface-hub>=0.36.2",
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.1",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.70.0",
    "transformers>=4.57.6",
    "vllm==0.15.0",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
vllm = { url = "https://github.com/vllm-project/vllm/releases/download/v0.15.0/vllm-0.15.0+cu130-cp38-abi3-manylinux_2_35_aarch64.whl" }
